inherit_gem:
  ns-rubocop:
    - default.yml
Rails:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/integration/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false
