Rails:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/integration/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false
